In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model


In [2]:
df=pd.read_csv("homeprices2.csv")

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
median_bedrooms=df.bedrooms.median()

In [5]:
median_bedrooms

4.0

In [6]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)

In [7]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [9]:
reg.predict([[3200,5,12]])

C:\Users\Mansi\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([658086.60156634])

In [10]:
reg.coef_


array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
reg.intercept_

221323.00186540384

Exercise:
In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score


In [12]:
df=pd.read_csv('hiring.csv')

In [13]:
df

experience  testscore  interviewscore  salary
0        NaN        8.0               9   50000
1        NaN        8.0               6   45000
2       five        6.0               7   60000
3        two       10.0              10   65000
4      seven        9.0               6   70000
5      three        7.0              10   62000
6        ten        NaN               7   72000
7     eleven        7.0               8   80000

In [14]:
median_test_score=df.testscore.median()

In [28]:
import math
mean_test_score=math.floor(df.testscore.mean())
mean_test_score

7

In [16]:
median_test_score

8.0

In [17]:
df.testscore

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     NaN
7     7.0
Name: testscore, dtype: float64

In [18]:
df.testscore=df.testscore.fillna(median_test_score)

In [19]:
df

experience  testscore  interviewscore  salary
0        NaN        8.0               9   50000
1        NaN        8.0               6   45000
2       five        6.0               7   60000
3        two       10.0              10   65000
4      seven        9.0               6   70000
5      three        7.0              10   62000
6        ten        8.0               7   72000
7     eleven        7.0               8   80000

In [20]:
df.experience=df.experience.fillna('zero')

In [21]:
df

experience  testscore  interviewscore  salary
0       zero        8.0               9   50000
1       zero        8.0               6   45000
2       five        6.0               7   60000
3        two       10.0              10   65000
4      seven        9.0               6   70000
5      three        7.0              10   62000
6        ten        8.0               7   72000
7     eleven        7.0               8   80000

In [22]:

from word2number import w2n
df.experience=df.experience.apply(w2n.word_to_num)

In [23]:
df


experience  testscore  interviewscore  salary
0           0        8.0               9   50000
1           0        8.0               6   45000
2           5        6.0               7   60000
3           2       10.0              10   65000
4           7        9.0               6   70000
5           3        7.0              10   62000
6          10        8.0               7   72000
7          11        7.0               8   80000

In [24]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','testscore','interviewscore']],df.salary)

LinearRegression()

In [25]:
reg.predict([[2,9,6]])

C:\Users\Mansi\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [26]:
reg.predict([[12,10,10]])

C:\Users\Mansi\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])